name: Test Google Cloud Authentication

on:
  workflow_dispatch:  # allows manual run from the Actions tab

permissions:
  contents: read
  id-token: write  # required for Workload Identity Federation (OIDC)

jobs:
  gcp-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Verify Google Cloud access
        run: |
          echo " Successfully authenticated to GCP!"
          echo " Active credentials:"
          gcloud auth list
          echo " Current project:"
          gcloud config list project
